import React, { useEffect, useRef, useState } from "react";
import { ArrowRight, BookOpen, Bot, ChevronRight, Clock3, Download, FileJson, Leaf, Link2, Loader2, Menu, RotateCcw, Sparkles, Sprout, X } from "lucide-react";

const WEBHOOK_URL = import.meta.env.VITE_WEBHOOK_URL;
const EXAMPLES = ["Python Programming", "Digital Marketing", "Public Speaking", "Data Analysis with Excel"];
const LINES = ["Planting your seed…", "Growing the first branches…", "Unfurling the lessons…", "Almost in bloom…"];
const steps = [["01", "Plant your idea", "Enter any topic, skill, or subject you want to explore."], ["02", "Shape the learning path", "AI turns your idea into a logical sequence of modules."], ["03", "Learn, edit, and share", "Refine your plan, follow the resources, or export a PDF."]];

export default function App() {
  const [topic,setTopic]=useState(""); const [status,setStatus]=useState("idle"); const [error,setError]=useState(""); const [data,setData]=useState(null); const [line,setLine]=useState(LINES[0]); const [menu,setMenu]=useState(false); const [page,setPage]=useState(()=>location.hash.slice(1)||"home"); const input=useRef(null);
  useEffect(()=>{if(status!=="loading")return;let i=0;const id=setInterval(()=>{i=(i+1)%LINES.length;setLine(LINES[i])},1400);return()=>clearInterval(id)},[status]);
  async function grow(){const final=topic.trim();if(!final){setError("Type a topic first.");setStatus("error");return}if(!WEBHOOK_URL||WEBHOOK_URL.trim()===""||WEBHOOK_URL.includes("YOUR-N8N-DOMAIN")){setError("Add your active n8n webhook URL in .env first.");setStatus("error");return}setStatus("loading");try{const res=await fetch(WEBHOOK_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topic:final})});if(!res.ok)throw new Error(`Server returned ${res.status}`);const raw=await res.json();setData(raw.text?JSON.parse(raw.text):raw.answers?JSON.parse(raw.answers):typeof raw==="string"?JSON.parse(raw):raw);setStatus("done")}catch(e){setError(`Check your n8n workflow and webhook URL. (${e.message})`);setStatus("error")}}
  const go=()=>document.querySelector("#studio")?.scrollIntoView({behavior:"smooth"});
  const navigate=(next)=>{location.hash=next;setPage(next);setMenu(false);window.scrollTo(0,0)};
  if(page!=="home") return <DetailPage page={page} navigate={navigate}/>;
  return <main><nav><button className="brand" onClick={()=>navigate("home")}><i><Sprout size={20}/></i>Sapling</button><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><div className={`links ${menu?"open":""}`}><button className="nav-item" onClick={()=>navigate("how")}>How it works</button><button className="nav-item" onClick={()=>navigate("features")}>Features</button><button className="nav-item" onClick={()=>navigate("docs")}>Docs</button><button onClick={go}>Build a curriculum <ArrowRight size={15}/></button></div></nav>
  <section id="studio" className="studio-section"><header><span>THE SAPLING STUDIO</span><h2>What would you like<br/>to <em>grow?</em></h2><p>Give us a topic. We’ll turn it into a real, usable learning plan.</p></header>{status!=="done"?<div className="studio"><div className="composer"><Sparkles size={19}/><input ref={input} value={topic} onChange={e=>setTopic(e.target.value)} onKeyDown={e=>e.key==="Enter"&&grow()} placeholder="Try ‘UX Design Fundamentals’"/><button onClick={grow} disabled={status==="loading"}>{status==="loading"?<Loader2 className="spin" size={17}/>:<Sprout size={17}/>}{status==="loading"?"Growing…":"Grow it"}</button></div><div className="chips">{EXAMPLES.map(x=><button key={x} onClick={()=>{setTopic(x);input.current?.focus()}}>{x}</button>)}</div>{status==="loading"&&<div className="state"><Sprout className="bounce"/>{line}</div>}{status==="error"&&<div className="error"><b>Couldn’t grow that yet.</b> {error}</div>}<small className="note"><Bot size={14}/> Powered by your n8n + Google Gemini workflow</small></div>:<CurriculumResult data={data} reset={()=>{setData(null);setStatus("idle");setTopic("")}}/>}</section>
  <section id="how" className="how"><div><span>SIMPLE BY DESIGN</span><h2>A better way to<br/>plan <em>learning.</em></h2><p>No blank-page paralysis. No scattered bookmarks. Just a focused path from curiosity to confidence.</p><a href="#studio">Create your first curriculum <ArrowRight size={16}/></a></div><div className="step-list">{steps.map(s=><article key={s[0]}><b>{s[0]}</b><div><h3>{s[1]}</h3><p>{s[2]}</p></div><ChevronRight size={18}/></article>)}</div></section>
  <section id="features" className="features"><img src="https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1000&q=85" alt="Person studying on a laptop"/><div><span>BUILT FOR REAL PROGRESS</span><h2>Everything you need to keep moving.</h2>{[[FileJson,"Structured from the start","Modules, lessons, and resource prompts—always in a sensible order."],[Clock3,"Save hours of planning","Turn any learning goal into a strong first draft in moments."],[Download,"Take it anywhere","Edit your plan or download a polished PDF whenever you’re ready."]].map(([Icon,title,text])=><article className="feature" key={title}><i><Icon size={19}/></i><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
  <section id="examples" className="examples"><header><span>IDEAS IN BLOOM</span><h2>Made for every<br/><em>kind of learner.</em></h2></header><div className="cards">{[["Career switcher","Learn data analysis","Excel · SQL · Dashboards"],["Creative explorer","Master visual storytelling","Composition · Light · Editing"],["Curious teacher","Build a better workshop","Outcomes · Activities · Assessments"]].map((c,i)=><article key={c[0]} className={`card c${i}`}><span>{c[0]}</span><h3>{c[1]}</h3><p>{c[2]}</p><button><ArrowRight size={18}/></button></article>)}</div></section>
  <section id="docs" className="docs"><div><span>HELPFUL FROM DAY ONE</span><h2>Built to be easy.<br/><em>Documented, too.</em></h2><p>Need to connect your n8n workflow or understand the curriculum format? Start here.</p></div><div>{[[BookOpen,"Getting started","Generate your first curriculum","#studio"],[Link2,"Connect n8n","Set up your workflow","https://docs.n8n.io/"],[FileJson,"Curriculum format","Understand your output","#features"]].map(([Icon,title,text,url])=><a key={title} href={url} target={url.startsWith("http")?"_blank":undefined} rel="noreferrer"><Icon size={22}/><b>{title}</b><small>{text} <ArrowRight size={15}/></small></a>)}</div></section>
  <footer><a className="brand" href="#home"><i><Sprout size={18}/></i>Sapling</a><p>Plant a topic. Grow a curriculum.</p><div><a href="#how">How it works</a><a href="#features">Features</a><a href="#docs">Documentation</a></div><small>© 2026 Sapling. Grown with intention.</small></footer></main>;
}
function Result({data,reset}){return <div className="result"><div className="result-head"><div><span>YOUR CURRICULUM</span><h2>{data?.topic||"Curriculum"}</h2><p>{(data?.modules||[]).length} modules, grown just now</p></div><div><button onClick={reset}>New topic</button><button className="primary" onClick={()=>window.print()}><Download size={15}/> PDF</button></div></div>{(data?.modules||[]).map((m,i)=><article className="module" key={i}><b>{String(i+1).padStart(2,"0")}</b><div><h3>{m.title}</h3>{(m.lessons||[]).map((l,j)=><div className="lesson" key={j}><b>{l.title}</b><small>{(l.resources||[]).join(" · ")}</small></div>)}</div></article>)}</div>}

function curriculumMarkup(data) {
  const safe=(value="")=>String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");
  const modules=(data?.modules||[]).map((mod,index)=>`<section><h2>${index+1}. ${safe(mod.title)}</h2>${(mod.lessons||[]).map((lesson,lessonIndex)=>`<article><h3>${index+1}.${lessonIndex+1} ${safe(lesson.title)}</h3>${(lesson.resources||[]).length?`<p><b>Resources:</b> ${lesson.resources.map(safe).join(" · ")}</p>`:""}</article>`).join("")}</section>`).join("");
  return `<html><head><meta charset="utf-8"><title>${safe(data?.topic||"Curriculum")}</title><style>body{font:16px Arial,sans-serif;color:#20382e;max-width:800px;margin:48px auto;line-height:1.55}h1{font:700 38px Georgia,serif;margin:0 0 6px}h2{font:700 23px Georgia,serif;border-bottom:2px solid #d8e4d7;padding:26px 0 9px}h3{margin:17px 0 5px;font-size:16px}article{padding:10px 14px;background:#f6f9f4;border-radius:7px;margin:10px 0}p{margin:0;color:#59665e}.meta{color:#7a847c;margin-bottom:22px}@media print{body{margin:25px}}</style></head><body><h1>${safe(data?.topic||"Curriculum")}</h1><p class="meta">Generated by Sapling · ${new Date().toLocaleDateString()}</p>${modules}</body></html>`;
}
function downloadFile(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const link=document.createElement("a");link.href=url;link.download=name;link.click();URL.revokeObjectURL(url)}
function markdown(data){return `# ${data?.topic||"Curriculum"}\n\n${(data?.modules||[]).map((m,i)=>`## ${i+1}. ${m.title}\n${(m.lessons||[]).map((l,j)=>`### ${i+1}.${j+1} ${l.title}\n${(l.resources||[]).length?`Resources: ${(l.resources||[]).join(" · ")}`:""}`).join("\n\n")}`).join("\n\n")}`}
function CurriculumResult({data,reset}){const [exportOpen,setExportOpen]=useState(false);const title=(data?.topic||"curriculum").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");const print=()=>{setExportOpen(false);const win=window.open("","_blank");if(!win){alert("Please allow pop-ups to export the PDF.");return}win.document.open();win.document.write(curriculumMarkup(data));win.document.close();win.onload=()=>{win.focus();win.print();win.opener=null}};const word=()=>{setExportOpen(false);downloadFile(`${title}.doc`,curriculumMarkup(data),"application/msword")};return <div className="result"><div className="result-head"><div><span>YOUR CURRICULUM</span><h2>{data?.topic||"Curriculum"}</h2><p>{(data?.modules||[]).length} modules, grown just now</p></div><div className="result-actions"><button onClick={reset}>New topic</button><div className="export-picker"><button className="primary" onClick={()=>setExportOpen(!exportOpen)}><Download size={15}/> Export</button>{exportOpen&&<div className="export-menu"><button onClick={print}>Download PDF</button><button onClick={word}>Download Word</button></div>}</div></div></div>{(data?.modules||[]).map((m,i)=><article className="module" key={i}><b>{String(i+1).padStart(2,"0")}</b><div><h3>{m.title}</h3>{(m.lessons||[]).map((l,j)=><div className="lesson" key={j}><b>{l.title}</b><small>{(l.resources||[]).join(" · ")}</small></div>)}</div></article>)}</div>}

function DetailPage({page,navigate}) {const [menu,setMenu]=useState(false);
  const goStudio=()=>{navigate("home");setTimeout(()=>document.querySelector("#studio")?.scrollIntoView({behavior:"smooth"}),60)};
  const navTo=(next)=>{setMenu(false);navigate(next)};
  const content={
    how:{eyebrow:"THE SAPLING METHOD",title:"From a small idea to a learning path you can actually follow.",intro:"Sapling gives your curiosity a useful structure. No complicated setup—just one topic and a clear next step.",image:"https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=85",items:[["01","Tell us what you want to learn","Start broad or be wonderfully specific. ‘Photography’, ‘Python for finance’, or ‘a workshop on better feedback’ all work."],["02","Let AI build the first draft","Sapling organizes concepts into modules and lessons in a sequence that makes sense."],["03","Make it your own","Use the generated plan as a strong foundation. Adjust the pace, edit topics, and share it as a PDF."]]},
    features:{eyebrow:"POWERFUL, NOT COMPLICATED",title:"A calm workspace for ambitious learning.",intro:"Every detail is designed to help you go from intent to action without getting in your way.",image:"https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=85",items:[["Structured curricula","Get a clear progression of modules, lessons, and resource prompts—not a wall of generic advice."],["Fast first drafts","Turn planning that normally takes hours into a thoughtful starting point in seconds."],["Shareable outputs","Create something useful for yourself, a student, or your team, then download it when ready."]]},
    docs:{eyebrow:"GUIDES & RESOURCES",title:"Everything you need to start growing.",intro:"A few practical notes to help you connect Sapling and get the most from every curriculum.",image:"https://images.unsplash.com/photo-1456324504439-367cee3b3c32?auto=format&fit=crop&w=1200&q=85",items:[["Getting started","Choose a topic, press Grow it, then use the curriculum as your personal roadmap."],["Connect your n8n webhook","Open the project’s .env file and replace the placeholder VITE_WEBHOOK_URL with your active n8n production webhook."],["Expected curriculum format","Sapling displays a topic, an array of modules, lessons within each module, and an optional list of resources per lesson."]]}
  }[page]||null;
  if(!content){navigate("home");return null}
  return <main className="detail-page"><nav><button className="brand" onClick={()=>navTo("home")}><i><Sprout size={20}/></i>Sapling</button><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><div className={`links ${menu?"open":""}`}><button className="nav-item" onClick={()=>navTo("how")}>How it works</button><button className="nav-item" onClick={()=>navTo("features")}>Features</button><button className="nav-item" onClick={()=>navTo("docs")}>Docs</button><button onClick={goStudio}>Build a curriculum <ArrowRight size={15}/></button></div></nav><section className="detail-hero"><div><span>{content.eyebrow}</span><h1>{content.title}</h1><p>{content.intro}</p><button className="primary" onClick={goStudio}>Try Sapling <ArrowRight size={17}/></button></div><img src={content.image} alt="Learning and planning"/></section><section className="detail-list">{content.items.map((item,i)=><article key={item[0]}><b>{String(i+1).padStart(2,"0")}</b><div><h2>{item[0]}</h2><p>{item[1]}</p></div></article>)}</section><section className="detail-cta"><Sparkles size={23}/><h2>Ready to grow something useful?</h2><p>Start with one topic. Let Sapling take care of the first outline.</p><button onClick={goStudio}>Go to the studio <ArrowRight size={16}/></button></section><footer><button className="brand" onClick={()=>navigate("home")}><i><Sprout size={18}/></i>Sapling</button><p>Plant a topic. Grow a curriculum.</p><div><button onClick={()=>navigate("how")}>How it works</button><button onClick={()=>navigate("features")}>Features</button><button onClick={()=>navigate("docs")}>Documentation</button></div><small>© 2026 Sapling. Grown with intention.</small></footer></main>
}
